
package com.test.springcxfwebservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestCxfWebService", targetNamespace = "http://springcxfwebservice.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestCxfWebService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testMethod", targetNamespace = "http://springcxfwebservice.test.com/", className = "com.test.springcxfwebservice.TestMethod")
    @ResponseWrapper(localName = "testMethodResponse", targetNamespace = "http://springcxfwebservice.test.com/", className = "com.test.springcxfwebservice.TestMethodResponse")
    public String testMethod();

}
