
package com.test.springcxfwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestCxfWebServiceService", targetNamespace = "http://springcxfwebservice.test.com/", wsdlLocation = "http://localhost:8081/ws/test?wsdl")
public class TestCxfWebServiceService
    extends Service
{

    private final static URL TESTCXFWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTCXFWEBSERVICESERVICE_EXCEPTION;
    private final static QName TESTCXFWEBSERVICESERVICE_QNAME = new QName("http://springcxfwebservice.test.com/", "TestCxfWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/test?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTCXFWEBSERVICESERVICE_WSDL_LOCATION = url;
        TESTCXFWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TestCxfWebServiceService() {
        super(__getWsdlLocation(), TESTCXFWEBSERVICESERVICE_QNAME);
    }

    public TestCxfWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTCXFWEBSERVICESERVICE_QNAME, features);
    }

    public TestCxfWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTCXFWEBSERVICESERVICE_QNAME);
    }

    public TestCxfWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTCXFWEBSERVICESERVICE_QNAME, features);
    }

    public TestCxfWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestCxfWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestCxfWebService
     */
    @WebEndpoint(name = "TestCxfWebServicePort")
    public TestCxfWebService getTestCxfWebServicePort() {
        return super.getPort(new QName("http://springcxfwebservice.test.com/", "TestCxfWebServicePort"), TestCxfWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestCxfWebService
     */
    @WebEndpoint(name = "TestCxfWebServicePort")
    public TestCxfWebService getTestCxfWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://springcxfwebservice.test.com/", "TestCxfWebServicePort"), TestCxfWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTCXFWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TESTCXFWEBSERVICESERVICE_EXCEPTION;
        }
        return TESTCXFWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
