
package com.test.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestServiceImpl", targetNamespace = "http://impl.webservice.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServiceImpl {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://impl.webservice.test.com/", className = "com.test.webservice.impl.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://impl.webservice.test.com/", className = "com.test.webservice.impl.LoginResponse")
    @Action(input = "http://impl.webservice.test.com/TestServiceImpl/loginRequest", output = "http://impl.webservice.test.com/TestServiceImpl/loginResponse")
    public void login();

}
