
package com.test.restspringcxfwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestRestCxfWebServiceService", targetNamespace = "http://restspringcxfwebservice.test.com/", wsdlLocation = "http://localhost:8081/ws/test2/testRestMethoddd?wsdl")
public class TestRestCxfWebServiceService
    extends Service
{

    private final static URL TESTRESTCXFWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTRESTCXFWEBSERVICESERVICE_EXCEPTION;
    private final static QName TESTRESTCXFWEBSERVICESERVICE_QNAME = new QName("http://restspringcxfwebservice.test.com/", "TestRestCxfWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/test2/testRestMethoddd?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTRESTCXFWEBSERVICESERVICE_WSDL_LOCATION = url;
        TESTRESTCXFWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TestRestCxfWebServiceService() {
        super(__getWsdlLocation(), TESTRESTCXFWEBSERVICESERVICE_QNAME);
    }

    public TestRestCxfWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTRESTCXFWEBSERVICESERVICE_QNAME, features);
    }

    public TestRestCxfWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTRESTCXFWEBSERVICESERVICE_QNAME);
    }

    public TestRestCxfWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTRESTCXFWEBSERVICESERVICE_QNAME, features);
    }

    public TestRestCxfWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestRestCxfWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestRestCxfWebService
     */
    @WebEndpoint(name = "TestRestCxfWebServicePort")
    public TestRestCxfWebService getTestRestCxfWebServicePort() {
        return super.getPort(new QName("http://restspringcxfwebservice.test.com/", "TestRestCxfWebServicePort"), TestRestCxfWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestRestCxfWebService
     */
    @WebEndpoint(name = "TestRestCxfWebServicePort")
    public TestRestCxfWebService getTestRestCxfWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://restspringcxfwebservice.test.com/", "TestRestCxfWebServicePort"), TestRestCxfWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTRESTCXFWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TESTRESTCXFWEBSERVICESERVICE_EXCEPTION;
        }
        return TESTRESTCXFWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
